name: video_editor_example
description: The example project for the video_editor package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_editor_2:
    path: ../
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  fraction: ^4.1.4
  helpers: ^1.1.4
  image_picker: ^0.8.6+1
  path: ^1.8.2
  video_player: ^2.5.1
  path_provider: ^2.0.12
  cross_file: ^0.3.3+4
  get_thumbnail_video: ^0.6.0
  ffmpeg_wasm: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
